import os

SECRET_KEY = os.environ.get('SECRET_KEY')
SSL_DISABLE = False
SQLALCHEMY_COMMIT_ON_TEARDOWN = True
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_RECORD_QUERIES = True
MAIL_SERVER = 'smtp.googlemail.com'
MAIL_PORT = 587
MAIL_USE_TLS = True
MAIL_USERNAME = os.environ.get('MAIL_USERNAME')
MAIL_PASSWORD = os.environ.get('MAIL_PASSWORD')
MESH_MAIL_SUBJECT_PREFIX = '[Mesh]'
MESH_ADMIN = os.environ.get('FLASKY_ADMIN')