"""upgrade relationship

Revision ID: 4c383234ca6d
Revises: 96529e3fe19e
Create Date: 2017-08-16 23:32:00.966948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c383234ca6d'
down_revision = '96529e3fe19e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('has_category_post_id_fkey', 'has_category', type_='foreignkey')
    op.create_foreign_key(None, 'has_category', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'has_category', type_='foreignkey')
    op.create_foreign_key('has_category_post_id_fkey', 'has_category', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
