"""empty message

Revision ID: 710d9f66b7d4
Revises: 95b31f3908b9
Create Date: 2019-02-09 10:53:29.232163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710d9f66b7d4'
down_revision = '95b31f3908b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'preview_html')
    op.drop_column('posts', 'preview')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('preview', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('preview_html', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
