"""empty message

Revision ID: 725d05123af2
Revises: 
Create Date: 2018-01-30 14:54:40.959751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '725d05123af2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_url', sa.String(length=125), nullable=True))
    op.add_column('posts', sa.Column('preview', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('preview_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'preview_html')
    op.drop_column('posts', 'preview')
    op.drop_column('posts', 'image_url')
    # ### end Alembic commands ###
